# Generated by Django 2.1.5 on 2020-11-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigoProducto', models.CharField(max_length=20)),
                ('cantidadProducto', models.IntegerField()),
                ('fotoProducto', models.ImageField(blank=True, upload_to='producto/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Categoria')),
            ],
        ),
    ]
