# Generated by Django 2.1.5 on 2020-11-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioProducto',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
