# Generated by Django 2.1.5 on 2020-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_producto_precioproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fotoProducto',
            new_name='imagenProducto',
        ),
    ]
